### ISSUE TITLE
Can't deploy full helm charts without values file

### ISSUE THREAD

**Issue by ChrisKujawa** [zeebe-io/zeebe-full-helm#85] opened 2020-08-03 12:35 UTC
With just running `helm install zeebe-cluster zeebe/zeebe-full` I exepct to be able to deploy the complete full helm  chart, but it turns out that this fails.

The standalone gateway keeps in the container creating phase.

```
[zell zell-test-gw/ ns:zell-test-gw]$ kgpo
NAME                                                           READY   STATUS              RESTARTS   AGE
elasticsearch-master-0                                         1/1     Running             0          82s
elasticsearch-master-1                                         1/1     Running             0          82s
elasticsearch-master-2                                         1/1     Running             0          82s
zeebe-cluster-nginx-ingress-controller-89b6fcbb6-j8l72         1/1     Running             0          82s
zeebe-cluster-nginx-ingress-default-backend-7c987dd75d-kr8hp   1/1     Running             0          82s
zeebe-cluster-operate-6cbff9f89d-wx7jv                         1/1     Running             1          82s
zeebe-cluster-zeebe-0                                          1/1     Running             0          82s
zeebe-cluster-zeebe-1                                          1/1     Running             0          82s
zeebe-cluster-zeebe-2                                          1/1     Running             0          82s
zeebe-cluster-zeebe-gateway-d59f5845-2cvbb                     0/1     ContainerCreating   0          82s
```

```
[zell zell-test-gw/ ns:zell-test-gw]$ k describe pod zeebe-cluster-zeebe-gateway-d59f5845-2cvbb 
Name:           zeebe-cluster-zeebe-gateway-d59f5845-2cvbb
Namespace:      zell-test-gw
Priority:       0
Node:           gke-zeebe-cluster-default-pool-1f44de48-j12j/10.132.0.75
Start Time:     Mon, 03 Aug 2020 14:29:17 +0200
Labels:         app.kubernetes.io/component=gateway
                app.kubernetes.io/instance=zeebe-cluster
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=zeebe
                app.kubernetes.io/version=0.23.4
                helm.sh/chart=zeebe-0.0.127
                pod-template-hash=d59f5845
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/zeebe-cluster-zeebe-gateway-d59f5845
Containers:
  zeebe:
    Container ID:   
    Image:          camunda/zeebe:0.23.4
    Image ID:       
    Ports:          9600/TCP, 26500/TCP, 26502/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Readiness:      tcp-socket :gateway delay=20s timeout=1s period=5s #success=1 #failure=3
    Environment:
      ZEEBE_STANDALONE_GATEWAY:            true
      ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME:   zeebe-cluster-zeebe
      ZEEBE_GATEWAY_CLUSTER_MEMBERID:      zeebe-cluster-zeebe-gateway-d59f5845-2cvbb (v1:metadata.name)
      ZEEBE_LOG_LEVEL:                     info
      JAVA_TOOL_OPTIONS:                   -XX:MaxRAMPercentage=25.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log -XX:+ExitOnOutOfMemoryError
      ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT:  zeebe-cluster-zeebe:26502
      ZEEBE_GATEWAY_NETWORK_HOST:          0.0.0.0
      ZEEBE_GATEWAY_NETWORK_PORT:          26500
      ZEEBE_GATEWAY_CLUSTER_HOST:           (v1:status.podIP)
      ZEEBE_GATEWAY_CLUSTER_PORT:          26502
      ZEEBE_GATEWAY_MONITORING_HOST:       0.0.0.0
      ZEEBE_GATEWAY_MONITORING_PORT:       9600
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-p8rvq (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      zeebe-cluster-zeebe
    Optional:  false
  default-token-p8rvq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-p8rvq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age               From                                                   Message
  ----     ------       ----              ----                                                   -------
  Normal   Scheduled    69s               default-scheduler                                      Successfully assigned zell-test-gw/zeebe-cluster-zeebe-gateway-d59f5845-2cvbb to gke-zeebe-cluster-default-pool-1f44de48-j12j
  Warning  FailedMount  5s (x8 over 69s)  kubelet, gke-zeebe-cluster-default-pool-1f44de48-j12j  MountVolume.SetUp failed for volume "config" : configmap "zeebe-cluster-zeebe" not found
```

It search's for the configmap which seem not to be specified as default.

With the `zeebe-cluster` chart this seem to be possible.

```
[zell zell-test-gw/ ns:zell-test-gw]$ helm install zeebe-cluster zeebe/zeebe-cluster 
NAME: zeebe-cluster
LAST DEPLOYED: Mon Aug  3 14:34:25 2020
NAMESPACE: zell-test-gw
STATUS: deployed
REVISION: 1
NOTES:
______     ______     ______     ______     ______    
/\___  \   /\  ___\   /\  ___\   /\  == \   /\  ___\   
\/_/  /__  \ \  __\   \ \  __\   \ \  __<   \ \  __\   
  /\_____\  \ \_____\  \ \_____\  \ \_____\  \ \_____\ 
  \/_____/   \/_____/   \/_____/   \/_____/   \/_____/                                                                                                                                      

(zeebe-cluster - 0.0.128)

- Docker Image used for Broker: camunda/zeebe:0.23.4
- Cluster Name: "zeebe-cluster-zeebe"
- ElasticSearch Enabled: true - URL: http://elasticsearch-master:9200
- Kibana Enabled: false
- Prometheus Enabled: false
- Prometheus ServiceMonitor Enabled: false

The Cluster itself is not exposed as a service that means that you can use kubectl port-forward to access the Zeebe cluster from outside Kubernetes:

> kubectl port-forward svc/zeebe-cluster-zeebe-gateway 26500:26500 -n zell-test-gw

Now you can connect your workers and clients to `localhost:26500`
[zell zell-test-gw/ ns:zell-test-gw]$ kgpo -w
NAME                                           READY   STATUS              RESTARTS   AGE
elasticsearch-master-0                         0/1     Init:0/1            0          3s
elasticsearch-master-1                         0/1     Init:0/1            0          3s
elasticsearch-master-2                         0/1     Init:0/1            0          3s
zeebe-cluster-zeebe-0                          0/1     ContainerCreating   0          2s
zeebe-cluster-zeebe-1                          0/1     ContainerCreating   0          2s
zeebe-cluster-zeebe-gateway-6fcc4d5949-8vlnt   0/1     Running             0          3s
zeebe-cluster-zeebe-2                          0/1     Pending             0          0s
zeebe-cluster-zeebe-2                          0/1     Pending             0          1s
zeebe-cluster-zeebe-2                          0/1     ContainerCreating   0          1s
elasticsearch-master-2                         0/1     PodInitializing     0          10s
elasticsearch-master-2                         0/1     Running             0          11s
zeebe-cluster-zeebe-2                          0/1     Running             0          11s
elasticsearch-master-1                         0/1     PodInitializing     0          18s
zeebe-cluster-zeebe-0                          0/1     Running             0          18s
zeebe-cluster-zeebe-1                          0/1     Running             0          18s
elasticsearch-master-1                         0/1     Running             0          19s
zeebe-cluster-zeebe-gateway-6fcc4d5949-8vlnt   1/1     Running             0          24s

```

**Comment by salaboy** [comment] 2020-08-03 14:30
@Zelldon I am investigating this now.. can you please confirm that you didn't used any `values.yaml` file with the full chart? 
Also.. can you please share the pod details of the gateway deployment? 

In my GKE cluster:
```
salaboy> h install zeebe-cluster zeebe/zeebe-full
NAME: zeebe-cluster
LAST DEPLOYED: Mon Aug  3 15:28:02 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
______     ______     ______     ______     ______    
/\___  \   /\  ___\   /\  ___\   /\  == \   /\  ___\   
\/_/  /__  \ \  __\   \ \  __\   \ \  __<   \ \  __\   
  /\_____\  \ \_____\  \ \_____\  \ \_____\  \ \_____\ 
  \/_____/   \/_____/   \/_____/   \/_____/   \/_____/                                                                                                                                      

(zeebe-full - 0.0.85)

- Cluster Name: zeebe-cluster-zeebe
salaboy> k get pods 
NAME                                                          READY   STATUS    RESTARTS   AGE
elasticsearch-master-0                                        1/1     Running   0          118s
elasticsearch-master-1                                        1/1     Running   0          118s
elasticsearch-master-2                                        1/1     Running   0          118s
zeebe-cluster-nginx-ingress-controller-6455df9958-7pnbv       1/1     Running   0          118s
zeebe-cluster-nginx-ingress-default-backend-c99b7d5f4-g59k8   1/1     Running   0          118s
zeebe-cluster-operate-f7b9fddcd-mx7j9                         1/1     Running   1          118s
zeebe-cluster-zeebe-0                                         1/1     Running   0          118s
zeebe-cluster-zeebe-1                                         1/1     Running   0          118s
zeebe-cluster-zeebe-2                                         1/1     Running   0          118s
zeebe-cluster-zeebe-gateway-777c9c9b5-5c4w5                   1/1     Running   0          118s
```

**Comment by salaboy** [comment] 2020-08-03 14:31
@Zelldon can you check to make sure that we are deploying the same version of the chart?

**Comment by ChrisKujawa** [comment] 2020-08-03 14:33
Sorry you're right. I think I used the latest version but I will try again tomorrow to be sure.

**Comment by ChrisKujawa** [comment] 2020-08-03 14:34
For reference https://forum.zeebe.io/t/pod-stuck-on-containercreating/1497

**Comment by salaboy** [comment] 2020-08-04 07:32
@Zelldon it seems that the user in the forum reported that the problem is solved.. I wonder if you manage to reproduce the problem as well.. how..

**Comment by ChrisKujawa** [comment] 2020-08-04 09:17
@salaboy  I can reproduce it. The problem seems to be triggered by the release name. If I use `zeebe-cluster` as release name the gateway can't be deployed. If the name is different everything works fine.

With `zell-test` it works:
```
[zell ~/ ns:zell-test]$ helm install zell-test zeebe/zeebe-full
NAME: zell-test
LAST DEPLOYED: Tue Aug  4 11:06:37 2020
NAMESPACE: zell-test
STATUS: deployed
REVISION: 1
NOTES:
______     ______     ______     ______     ______    
/\___  \   /\  ___\   /\  ___\   /\  == \   /\  ___\   
\/_/  /__  \ \  __\   \ \  __\   \ \  __<   \ \  __\   
  /\_____\  \ \_____\  \ \_____\  \ \_____\  \ \_____\ 
  \/_____/   \/_____/   \/_____/   \/_____/   \/_____/                                                                                                                                      

(zeebe-full - 0.0.85)

- Cluster Name: zell-test-zeebe
[zell ~/ ns:zell-test]$ kgpo -w
NAME                                                      READY   STATUS              RESTARTS   AGE
elasticsearch-master-0                                    0/1     Init:0/1            0          13s
elasticsearch-master-1                                    0/1     Init:0/1            0          13s
elasticsearch-master-2                                    0/1     Init:0/1            0          13s
zell-test-nginx-ingress-controller-6486b58cdd-47wbq       0/1     Running             0          13s
zell-test-nginx-ingress-default-backend-76bb8647b-jp7lr   1/1     Running             0          13s
zell-test-operate-ff6dfcff8-crhkd                         1/1     Running             0          13s
zell-test-zeebe-0                                         0/1     ContainerCreating   0          13s
zell-test-zeebe-1                                         0/1     Running             0          13s
zell-test-zeebe-2                                         0/1     ContainerCreating   0          13s
zell-test-zeebe-gateway-55656cd485-sn7bs                  0/1     Running             0          13s
elasticsearch-master-1                                    0/1     PodInitializing     0          16s
elasticsearch-master-1                                    0/1     Running             0          17s
zell-test-nginx-ingress-controller-6486b58cdd-47wbq       1/1     Running             0          19s
zell-test-zeebe-2                                         0/1     Running             0          19s
zell-test-zeebe-0                                         0/1     Running             0          19s
zell-test-zeebe-gateway-55656cd485-sn7bs                  1/1     Running             0          24s
elasticsearch-master-0                                    0/1     PodInitializing     0          24s
elasticsearch-master-0                                    0/1     Running             0          25s
elasticsearch-master-2                                    0/1     PodInitializing     0          26s
elasticsearch-master-2                                    0/1     Running             0          27s
zell-test-zeebe-2                                         1/1     Running             0          46s
zell-test-zeebe-1                                         1/1     Running             0          48s
zell-test-zeebe-0                                         1/1     Running             0          52s
zell-test-operate-ff6dfcff8-crhkd                         0/1     Error               0          62s
zell-test-operate-ff6dfcff8-crhkd                         1/1     Running             1          63s
elasticsearch-master-1                                    1/1     Running             0          77s
elasticsearch-master-2                                    1/1     Running             0          82s
elasticsearch-master-0                                    1/1     Running             0          87s
^C[zell ~/ ns:zell-test]$ helm uninstall zell-test
release "zell-test" uninstalled

```

With `zeebe-cluster` it doesn't.

```
[zell ~/ ns:zell-test]$ helm install zeebe-cluster zeebe/zeebe-full
NAME: zeebe-cluster
LAST DEPLOYED: Tue Aug  4 11:09:42 2020
NAMESPACE: zell-test
STATUS: deployed
REVISION: 1
NOTES:
______     ______     ______     ______     ______    
/\___  \   /\  ___\   /\  ___\   /\  == \   /\  ___\   
\/_/  /__  \ \  __\   \ \  __\   \ \  __<   \ \  __\   
  /\_____\  \ \_____\  \ \_____\  \ \_____\  \ \_____\ 
  \/_____/   \/_____/   \/_____/   \/_____/   \/_____/                                                                                                                                      

(zeebe-full - 0.0.85)

- Cluster Name: zeebe-cluster-zeebe
[zell ~/ ns:zell-test]$ kgpo -w
NAME                                                           READY   STATUS              RESTARTS   AGE
elasticsearch-master-0                                         0/1     Init:0/1            0          18s
elasticsearch-master-1                                         0/1     Init:0/1            0          18s
elasticsearch-master-2                                         0/1     Running             0          18s
zeebe-cluster-nginx-ingress-controller-589f56979d-gq7qx        1/1     Running             0          18s
zeebe-cluster-nginx-ingress-default-backend-7c987dd75d-tprjf   1/1     Running             0          19s
zeebe-cluster-operate-6cbff9f89d-b8hcm                         1/1     Running             0          19s
zeebe-cluster-zeebe-0                                          0/1     ContainerCreating   0          18s
zeebe-cluster-zeebe-1                                          0/1     Running             0          18s
zeebe-cluster-zeebe-2                                          0/1     ContainerCreating   0          18s
zeebe-cluster-zeebe-gateway-d59f5845-twjr4                     0/1     ContainerCreating   0          18s
zeebe-cluster-zeebe-2                                          0/1     Running             0          23s
elasticsearch-master-1                                         0/1     PodInitializing     0          24s
zeebe-cluster-zeebe-0                                          0/1     Running             0          25s
elasticsearch-master-0                                         0/1     PodInitializing     0          25s
elasticsearch-master-1                                         0/1     Running             0          25s
elasticsearch-master-0                                         0/1     Running             0          26s
zeebe-cluster-zeebe-2                                          1/1     Running             0          49s
zeebe-cluster-zeebe-0                                          1/1     Running             0          50s
zeebe-cluster-zeebe-1                                          1/1     Running             0          53s
zeebe-cluster-operate-6cbff9f89d-b8hcm                         0/1     Error               0          75s
zeebe-cluster-operate-6cbff9f89d-b8hcm                         1/1     Running             1          76s
elasticsearch-master-2                                         1/1     Running             0          76s
elasticsearch-master-0                                         1/1     Running             0          79s
elasticsearch-master-1                                         1/1     Running             0          89s
c^C[zell ~/ ns:zell-test]$ k describe pod zeebe-cluster-zeebe-gateway-d59f5845-twjr4 
Name:           zeebe-cluster-zeebe-gateway-d59f5845-twjr4
Namespace:      zell-test
Priority:       0
Node:           gke-zeebe-cluster-default-pool-1f44de48-s50z/10.132.0.92
Start Time:     Tue, 04 Aug 2020 11:09:45 +0200
Labels:         app.kubernetes.io/component=gateway
                app.kubernetes.io/instance=zeebe-cluster
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=zeebe
                app.kubernetes.io/version=0.23.4
                helm.sh/chart=zeebe-0.0.127
                pod-template-hash=d59f5845
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/zeebe-cluster-zeebe-gateway-d59f5845
Containers:
  zeebe:
    Container ID:   
    Image:          camunda/zeebe:0.23.4
    Image ID:       
    Ports:          9600/TCP, 26500/TCP, 26502/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Readiness:      tcp-socket :gateway delay=20s timeout=1s period=5s #success=1 #failure=3
    Environment:
      ZEEBE_STANDALONE_GATEWAY:            true
      ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME:   zeebe-cluster-zeebe
      ZEEBE_GATEWAY_CLUSTER_MEMBERID:      zeebe-cluster-zeebe-gateway-d59f5845-twjr4 (v1:metadata.name)
      ZEEBE_LOG_LEVEL:                     info
      JAVA_TOOL_OPTIONS:                   -XX:MaxRAMPercentage=25.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log -XX:+ExitOnOutOfMemoryError
      ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT:  zeebe-cluster-zeebe:26502
      ZEEBE_GATEWAY_NETWORK_HOST:          0.0.0.0
      ZEEBE_GATEWAY_NETWORK_PORT:          26500
      ZEEBE_GATEWAY_CLUSTER_HOST:           (v1:status.podIP)
      ZEEBE_GATEWAY_CLUSTER_PORT:          26502
      ZEEBE_GATEWAY_MONITORING_HOST:       0.0.0.0
      ZEEBE_GATEWAY_MONITORING_PORT:       9600
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rwlc4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      zeebe-cluster-zeebe
    Optional:  false
  default-token-rwlc4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rwlc4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                   From                                                   Message
  ----     ------       ----                  ----                                                   -------
  Normal   Scheduled    4m37s                 default-scheduler                                      Successfully assigned zell-test/zeebe-cluster-zeebe-gateway-d59f5845-twjr4 to gke-zeebe-cluster-default-pool-1f44de48-s50z
  Warning  FailedMount  27s (x10 over 4m37s)  kubelet, gke-zeebe-cluster-default-pool-1f44de48-s50z  MountVolume.SetUp failed for volume "config" : configmap "zeebe-cluster-zeebe" not found
  Warning  FailedMount  19s (x2 over 2m34s)   kubelet, gke-zeebe-cluster-default-pool-1f44de48-s50z  Unable to mount volumes for pod "zeebe-cluster-zeebe-gateway-d59f5845-twjr4_zell-test(c3fbcf07-35b8-4a8b-894a-17f4f5214172)": timeout expired waiting for volumes to attach or mount for pod "zell-test"/"zeebe-cluster-zeebe-gateway-d59f5845-twjr4". list of unmounted volumes=[config]. list of unattached volumes=[config default-token-rwlc4]
[zell ~/ ns:zell-test]$ 
```

**Comment by sebjonas** [comment] 2020-09-03 17:19
Hi, I was the user who reported it in the forum and actually been stuck **again** for some days creating a cluster and named it "zeebe-cluster". I wish I seen this discussion earlier ;). Now I will change name to "zb-cluster" ...

**Comment by salaboy** [comment] 2021-03-13 10:45
I will close this as it doesn't apply to new charts as far as I know if someone encounters this problem again please open a new issue

**Closed as completed by salaboy** 2021-03-13 10:45 UTC
Labels: bug
